Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 0
      MemorySize: 10240
      Handler: com.minhle.HelloWorld
      CodeUri: C:\Users\adam\IdeaProjects\TestLambdaHelloWorld
      Runtime: java11